#!/usr/bin/env bash
#script using case
x=1
while [ $x -le 20 ]
do
	echo "$x"
	case $x in
	     4)
		echo "back luck from China"
		;;
	     9)
		echo "back luck from Japan"
		;;
	     17)
		echo "bad luck from Italy"
		;;
	esac
	((x++))
done
